// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/b398805089841f77ca89afe65d1d50908fa68d2f/website-scraper/index.d.ts

declare module websiteScraper {

    interface Url {
        url: string;
        filename: string;
    }
    interface Source {
        selector: string;
        attr: string;
    }

    interface SubDirectory {
        directory: string;
        extensions: string[];
    }

    interface RequestOptions {
        headers: any;
    }

    type Options = {
        urls: Array<string | Url>;
        directory: string;
        urlFilter?: (url: string) => boolean;
        filenameGenerator?: string;
        defaultFilename?: string;
        prettifyUrls?: boolean;
        sources?: Source[];
        subdirectories?: SubDirectory[] | null;
        request?: RequestOptions;
        recursive?: boolean;
        maxDepth?: number;
        ignoreErrors?: boolean;
    };

    interface Resource {
        url: string;
        filename: string;
        assets: Resource[];
    }
    interface Callback {
        (error: any | null, result: Resource[] | null): void;
    }

    interface Scrape {
        (options: Options, callback: Callback): void;
        (options: Options): Promise<Resource[]>;
    }
}

declare module 'website-scraper' {
// Type definitions for website-scraper v1.2.x
// Project: https://github.com/s0ph1e/node-website-scraper
// Definitions by: Christian Rackerseder <https://www.echooff.de>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

    import * as request from 'request';

    interface RequestOptions extends websiteScraper.RequestOptions {
        headers: request.Headers
    }

    interface Scrape extends websiteScraper.Scrape {}

    var scrape:websiteScraper.Scrape;

    export = scrape;
}
